// <auto-generated />
using EmployeeManagementWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementWebAPI.Migrations
{
    [DbContext(typeof(EmployeeManagementSystemDbContext))]
    [Migration("20221111151130_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementWebAPI.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMPLOYEE_NAME");

                    b.Property<string>("EmployeeRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMPLOYEE_ROLE");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MANAGER_NAME");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__CBA14F48C246D7C3");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
